#!/bin/sh

set -e

if [ "$1" = "purge" ]; then
    rmdir -p /usr/local/share/zsh/site-functions || true
fi

# Automatically added by dh_installdeb/11.1.6ubuntu1
dpkg-maintscript-helper symlink_to_dir /usr/share/doc/zsh zsh-common 5.0.7-3 -- "$@"
# End automatically added section
# Automatically added by dh_installmenu/11.1.6ubuntu1
if [ -x "`which update-menus 2>/dev/null`" ]; then update-menus ; fi
# End automatically added section

